### ISSUE TITLE
Exception (ubuntu 11.04)

### ISSUE THREAD

**Issue by lrkwz** [vintitres/gnome-shell-google-calendar#1]
Following the instructions given here http://www.webupd8.org/2011/09/google-calendar-gnome-shell-integration.html I've executed:

sudo apt-get install git-core python-gtk2 python-dbus python-gdata python-iso8601 python-gnomekeyring

but no python-iso8601 seems to be available.

Given this I've lanched the script which responds with

~/gnome-shell-google-calendar> ./gnome-shell-google-calendar.py 
Logging in as 'xxxx.xxxxxxxx@gmail.com'...
xxxx.xxxxxxxx@gmail.com's Calendar List:
  (...)
Checking if actual month events need update...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "./gnome-shell-google-calendar.py", line 152, in scheduler
    if self.months[get_month_key(datetime.now())].\
KeyError: (1314482400, 1317506399)

**Comment by vintitres** [comment]
Is "(...)" under "Calendar list:" just list of calendars, or there is some more output in between? If there is, please give me a few more lines to debug it.

**Comment by lrkwz** [comment]
I've omitted to copy it because there's the list of the names of my private calendars.

**Comment by lrkwz** [comment]
Sorry closed by error

**Comment by vintitres** [comment]
Does "Checking if actual month events need update..." show up immediately after list of calendars is shown, or is there an about minute pause before that happens?

**Comment by lrkwz** [comment]
It shows up after about a minute.

-Luca http://about.me/lrkwz

**Comment by vintitres** [comment]
Wierd, it looks like your gnome shell CalendarServer never asked for events, are you sure you have gnome 3?

**Comment by lrkwz** [comment]
Opps sorry I thought Unity will suffice for the dbus support.
-Luca http://about.me/lrkwz

**Comment by vintitres** [comment]
Maybe unity calendar has similar dbus support, but it would have to be implemented into script. I, unfortunately, don't have any unity environment to develop on right now.
