### ISSUE TITLE
accounts login failure

### ISSUE THREAD

**Issue by bmbaker** [vintitres/gnome-shell-google-calendar#18]
i was using this method on all my installs and it wked just super!
on my 12.04 install with gnome-shell 3.3.90 i am getting login errors!

bb@Dream-On-Test:~/gnome-shell-google-calendar$ ./gnome-shell-google-calendar.py *\* WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'** WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'Logging in as 'None'...0. xxxxxx@gmail.comPlease choose the Account: xxxxxx@gmail.comTraceback (most recent call last):  File "./gnome-shell-google-calendar.py", line 451, in <module>    account = oauth.oauth_prompt()  File "/home/bb/gnome-shell-google-calendar/oauth.py", line 25, in oauth_prompt    email = accounts[int(raw_input('Please choose the Account: '))]ValueError: invalid literal for int() with base 10: 'xxxxxx@gmail.com'bb@Dream-On-Test:~/gnome-shell-google-calendar$ ./gnome-shell-google-calendar.py *\* WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'** WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'Logging in as 'None'...0. xxxxxx@gmail.comPlease choose the Account: xxxxxx@gmail.comTraceback (most recent call last):  File "./gnome-shell-google-calendar.py", line 451, in <module>    account = oauth.oauth_prompt()  File "/home/bb/gnome-shell-google-calendar/oauth.py", line 25, in oauth_prompt    email = accounts[int(raw_input('Please choose the Account: '))]ValueError: invalid literal for int() with base 10: 'xxxxxx@gmail.com'

the names have been changed to protect the innocent :-)

**Comment by vintitres** [comment]
I believe that the problem you have is a result of change in authentication to gnome online accounts. You need to add your google account to gnome online accounts and then, before "Please choose account" there should be a numbered list of accounts, you just need to write a number of your account. I'm not sure what is the warning before about. You also can use old authentication method, by checkouting to branch "keyring".

**Comment by bmbaker** [comment]
ah thank you :-)
was so simple ........ too simple i was looking to hard for the obvious!
it even tells you what number is for the account in my case 0 :-)
thjanks for the quick reply :-)

**Comment by bmbaker** [comment]
hmmm i did as per your instructions which worked in the terminal but doesn't persist after even with the startup script running on boot from the startup applications!
someone on webupd8 also has the same issue ! cheers BB

**Comment by vintitres** [comment]
Try something like that in startup script on new version:
test@test-laptop:~$ /home/test/gnome-shell-google-calendar/gnome-shell-google-calendar.py --account test@gmail.com
I hope it helps
