### ISSUE TITLE
command line parameters

### ISSUE THREAD

**Issue by daandres** [vintitres/gnome-shell-google-calendar#19]
Hi, 

maybe you can add a parameter to the programm, so that it is possible to pre-select the account you want to use. 
This helpful when you want the script to be run in the autostart. 

Now it loos like this:

test@test-laptop:~$ /home/test/gnome-shell-google-calendar/gnome-shell-google-calendar.py
Logging in as 'None'...
0. test@gmail.com
Please choose the Account: 0

In future it can be :
test@test-laptop:~$ /home/test/gnome-shell-google-calendar/gnome-shell-google-calendar.py 0
or 
test@test-laptop:~$ /home/test/gnome-shell-google-calendar/gnome-shell-google-calendar.py test@gmail.com
or 
test@test-laptop:~$ /home/test/gnome-shell-google-calendar/gnome-shell-google-calendar.py --account test@gmail.com
test@test-laptop:~$ /home/test/gnome-shell-google-calendar/gnome-shell-google-calendar.py -a test@gmail.com

This would be great :)

THX

**Comment by vintitres** [comment]
Isn't it enough that it remembers last used account?

**Comment by daandres** [comment]
oh i don't see that... 

but maybe it is good, because if you want to start with different launchers different accounts..

**Comment by vintitres** [comment]
Try something like that now:
test@test-laptop:~$ /home/test/gnome-shell-google-calendar/gnome-shell-google-calendar.py --account test@gmail.com
I hope it helps

**Comment by daandres** [comment]
it works... thanks
