### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by romainvv** [vintitres/gnome-shell-google-calendar#2]
Hi, 
Very nice idea.
I would like to use your code, to synchronise my google calendar with the gnome calendar.
I'm using Ubuntu11.10, i don't know if it can help you.
Here's the error i have got : 

./gnome-shell-google-calendar.py 
Logging in as 'romainvv'...
romainvv@gmail.com's Calendar List:
   romainvv@gmail.com
   Romain Van Vooren's Facebook Events
Checking if actual month events need update...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "./gnome-shell-google-calendar.py", line 152, in scheduler
    if self.months[get_month_key(datetime.now())].\
KeyError: (1316901600, 1320533999)

**Comment by vintitres** [comment]
I believe this is the same problem as in https://github.com/vintitres/gnome-shell-google-calendar/issues/1 (it works only with gnome3)

**Comment by romainvv** [comment]
Escuse me to bother you with that but please can you give me tips/links/irc to adapt your code to unity ?
I tried to find informations about dbus and the indicator applet on unity with cmd dbus-monitor.
I found path=/com/canonical/indicator/datetime/menu
Then with this I found this : http://indicator-datetime.sourcearchive.com/documentation/0.1.96-0ubuntu1/dbus-shared_8h_source.html
So i tried to modify that : 
busname = 'com.canonical.indicator.datetime'
    object_path = '/com/canonical/indicator/datetime/service'
and
@dbus.service.method('com.canonical.indicator.datetime', ...

But nothing goes better :s
Can you help me ?

**Comment by vintitres** [comment]
Try to run dbus-monitor command and do something to make unity calendar ask for events. In gnome 3 i get sth like that:

method call sender=:1.43 -> dest=org.gnome.Shell.CalendarServer serial=544 path=/org/gnome/Shell/CalendarServer; interface=org.gnome.Shell.CalendarServer; member=GetEvents
   int64 1319972400
   int64 1322996400
   boolean true
method return sender=:1.69 -> dest=:1.43 reply_serial=544
   array [
(...)
   ]
