### ISSUE TITLE
config.json file in home folder

### ISSUE THREAD

**Issue by simonbcn** [vintitres/gnome-shell-google-calendar#20]
I have added `/home/simon/sources/gnome-shell-extensions/gnome-shell-google-calendar/gnome-shell-google-calendar.py --account=mail@mail.es` to init apps in Ubuntu.
But when I start the gnome session, it creates config.json file in my home folder. This file should be created in the folder where it resides the `gnome-shell-google-calendar.py` or in a hidden folder with the other settings of this app.

**Comment by vintitres** [comment]
Now it shouldn't create config.json if used with --account flag,

**Comment by simonbcn** [comment]
Thanks, it works now.
