### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by ignition42** [vintitres/gnome-shell-google-calendar#22]
I have a problem with times, every event in my calendar have two hours of delay, I think because I have UTC+2 time and is not applied.

Sorry for my English I hope you understand.

**Comment by vintitres** [comment]
Are you sure that both your system calendar and google calendars are set to UTC+2? Beacuse it works all right for me in non UTC timezone.

**Comment by ignition42** [comment]
Thanks for anwering. Yes I'm sure. 
I've been testing. If I change the system timezone nothing changes and if I change the Google calendar timezone nothing either. When I say nothing changes I mean the time of event is still the same.

**Comment by vintitres** [comment]
The extension discarded timezone info, I think I fixed it in last commit. Please try it now.

**Comment by ignition42** [comment]
Now works.
I appreciate your work, thanks.
