### ISSUE TITLE
Removing the name of calendar that appears in events

### ISSUE THREAD

**Issue by bertrand47** [vintitres/gnome-shell-google-calendar#26]
Hi,
Is it possible to remove the name of my calendar, that appears within brackets after every event of my calendar. For me it's : (be) for example. I have no utility of that, and i'm using only one calendar and even if i add another one, The name of the event is enough for me.
Thanks for your help.

**Comment by vintitres** [comment]
Just run gnome-shell-google-calendar.py with --hide-cal option.

**Comment by bertrand47** [comment]
Thanks for your help, but could you please explain where  i find or insert this option ?

**Comment by vintitres** [comment]
```
python /path/to/script/gnome-shell-google-calendar.py --account your@mail.com --hide-cal
```

in console or in strartup configuration.

**Comment by bertrand47** [comment]
thanks.

**Comment by bertrand47** [comment]
It works well. Thanks
