### ISSUE TITLE
Can't exclude calendars with "Ö" in name

### ISSUE THREAD

**Issue by sojusnik** [vintitres/gnome-shell-google-calendar#28]
Hello,

currently it's not possible to exclude calenders with an "Ö", presumably with any other umlaut mark too, in .gnome-shell-google-calendar-excludes. Any other calendar without "special characters" is excluded correctly, but not the one with the "Ö" in it.

Hoping for a quick solution and wishing you all the best!

**Comment by vintitres** [comment]
commit 09c6353129681ca84f6af3fb8008f55707d08ffb should fix it

**Comment by sojusnik** [comment]
Thanks. Works well now.
