### ISSUE TITLE
How to see the ending time of an event?

### ISSUE THREAD

**Issue by sojusnik** [vintitres/gnome-shell-google-calendar#29]
Hello,

at the moment, your extension shows only the starting time of an event. Is there a possibility to see the ending time too?

Best wishes!

**Comment by vintitres** [comment]
This script actually sends ending times of events to the gnome shell CalendarServer, but it doesn't show it. I couldn't find an option in gsettings to change it, so i believe that it can't be done without modification of the CalendarServer.
