### ISSUE TITLE
GNOME 3.2 support?

### ISSUE THREAD

**Issue by 0rAX0** [vintitres/gnome-shell-google-calendar#3]
Hi, 

I just installed this under Arch from AUR: https://aur.archlinux.org/packages.php?ID=49468
I installed 'python2-iso8601' too. 

I'm getting:   File "/usr/bin/gnome-shell-google-calendar.py", line 6, in <module>
    import gtk
ImportError: No module named gtk

Is it compatible with 3.2?
Is there a way to use the User Accounts feature to pull the necessary information?

Thank you.

**Comment by ghost** [comment]
It works just fine with 3.2.

Download the git version and change it so that it runs with python2
 ( e.g. change #!/usr/bin/python to #!/usr/bin/python2 )

**Comment by 0rAX0** [comment]
Yeah, sorry to bother you. I found a workaround.
