### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by NaGeL182** [vintitres/gnome-shell-google-calendar#31]
Hello
I tried using this on Ubuntu Gnome remix 12.10 64-bit
and i got the following error:

Traceback (most recent call last):
  File "./gnome-shell-google-calendar.py", line 468, in <module>
    account = oauth.oauth_prompt()
  File "/home/nagel/gnome-shell-google-calendar/oauth.py", line 25, in oauth_prompt
    email = accounts[int(raw_input('Please choose the Account: '))]
ValueError: invalid literal for int() with base 10: 'nagel182@gmail.com'

help please.

**Comment by jayr0d** [comment]
See the following:

https://github.com/vintitres/gnome-shell-google-calendar/issues/18

http://askubuntu.com/questions/116041/help-with-installing-gnome-shell-google-calendar-extension

I think this issue comes up often...someone should write a patch...

**Comment by NaGeL182** [comment]
thank you.  it works
