### ISSUE TITLE
dbus.service:Unable to append

### ISSUE THREAD

**Issue by JohnKendrick** [vintitres/gnome-shell-google-calendar#4]
Hi,

I am running Ubuntu 11.10 with the gnome-shell.  I tried your python script and I see the following error.
Logging in as 'john@*******_'...
***_******@gmail.com's Calendar List:
   John 
   Music  Group
   Helen 
   Remember The Milk

GetEvents(since=1317035760, until=1320664560, force_reload=True)
  Getting events for: October 2011
  Month not yet downloaded
  Updating...
     Update months events around: October 2011 | months_back 2 | months_ahead 12
     Getting events from John ...
     Getting events from Music  Group ...
     Getting events from Helen ...
     Getting events from Remember The Milk ...
     #Updated events since August 2011 until October 2012
 #Returning 178 events...

ERROR:dbus.service:Unable to append ([('', 'CT-3506 (AM: MD)', '', False, 1319443200, 1319472000, {}), ('', 'Josh and ??', '', False, 1319115600, 1319119200, {}),  ,,,,, 
 ('', 'Tasks for 1/10', '', True, 1317423600, 1317510000, {})],) to message with signature a(sssbxxa{sv}): <type 'exceptions.TypeError'>: Expected a string or unicode object

My python is a bit rusty and I have no experience of the dbus API in python, so I am not sure where to look for the problem.

Thanks
John

**Comment by vintitres** [comment]
Please try it now.

**Comment by JohnKendrick** [comment]
Yes that fixed it.  Thanks
