### ISSUE TITLE
(la) suffix on every event

### ISSUE THREAD

**Issue by sifro** [vintitres/gnome-shell-google-calendar#8]
Hello,

every event displayed in gnome-shell-calendar contains a "(la)" suffix which shouldn't appear, as i never typed it in the event name in gcal.

ANy ideas?

See screenshot for details: www.ibrowsergame.it/la.jpg

**Comment by vintitres** [comment]
It is a shortcut of your calendar name, to hide it pull the newest version and run gnome-shell-google-calendar.py with --hide-cal option.

**Comment by sifro** [comment]
works great. thasnk
